package com.google.sample.mobileassistant;

import android.app.Activity;
import android.content.Intent;
import android.os.AsyncTask;
import android.os.Bundle;
import android.support.v4.app.Fragment;
import android.support.v4.app.FragmentManager;
import android.support.v4.widget.DrawerLayout;
import android.support.v7.app.ActionBar;
import android.support.v7.app.ActionBarActivity;
import android.util.Log;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;

import com.google.sample.mobileassistantbackend.shoppingAssistant.ShoppingAssistant;
import com.google.sample.mobileassistantbackend.shoppingAssistant.model.HistoryItemCollection;

import java.io.IOException;
import java.util.logging.Logger;

public class HistoryActivity extends ActionBarActivity
        implements NavigationDrawerFragment.NavigationDrawerCallbacks {

    private NavigationDrawerFragment mNavigationDrawerFragment;
    private DrawerLayout mDrawerLayout;

    /**
     * Used to store the last screen title. For use in {@link #restoreActionBar()}.
     */
    private CharSequence mTitle;

    /**
     * The class automatically generated by the Google App Engine backend
     * project, used to access the API easily from the Android application.
     */
    private ShoppingAssistant shoppingAssistantAPI;

    private static final Logger LOG = Logger
            .getLogger(MainActivity.class.getName());


    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_history);

        // Handle to the GAE endpoints in the backend
        shoppingAssistantAPI = CloudEndpointBuilderHelper.getEndpoints();

        mNavigationDrawerFragment = (NavigationDrawerFragment)
                getSupportFragmentManager().findFragmentById(R.id.navigation_drawer);
        mTitle = getTitle();

        // Set up the drawer.
        mNavigationDrawerFragment.setUp(
                R.id.navigation_drawer,
                (DrawerLayout) findViewById(R.id.drawer_layout_history));

        new getHistoryAsyncRetriever().execute();
    }

    @Override
    public void onNavigationDrawerItemSelected(int position) {
        // update the main content by replacing fragments
        FragmentManager fragmentManager = getSupportFragmentManager();
        fragmentManager.beginTransaction()
                .replace(R.id.container, PlaceholderFragment.newInstance(position + 1))
                .commit();
    }

    public void onSectionAttached(int number) {
        switch (number) {
            case 2:
                mTitle = getString(R.string.title_section2);
                Intent intent1 = new Intent(this, MainActivity.class);
                startActivity(intent1);
                break;
            case 3:
                mTitle = getString(R.string.title_section3);
                Intent intent2 = new Intent(this, BarcodeActivity.class);
                startActivity(intent2);
                break;
            case 4:
                mTitle = getString(R.string.title_section4);
                Intent intent3 = new Intent(this, CameraActivity.class);
                startActivity(intent3);
                break;
            case 6:
                mTitle = getString(R.string.title_section6);
                break;
            case 8:
                mTitle = getString(R.string.title_section8);
                Intent intent7 = new Intent(this, NearActivity.class);
                startActivity(intent7);
                break;
            case 9:
                mTitle = getString(R.string.title_section9);
                Intent intent8 = new Intent(this, SettingsActivity.class);
                startActivity(intent8);
                break;
            case 10:
                mTitle = getString(R.string.title_section10);
                SignInActivity.onSignOut(this);
                break;
        }
    }

    public void restoreActionBar() {
        ActionBar actionBar = getSupportActionBar();
//        actionBar.setBackgroundDrawable(new ColorDrawable(0xff8c1a));
        actionBar.setNavigationMode(ActionBar.NAVIGATION_MODE_STANDARD);
        actionBar.setDisplayShowTitleEnabled(true);
        actionBar.setTitle(mTitle);
    }


    /**
     * A placeholder fragment containing a simple view.
     */
    public static class PlaceholderFragment extends Fragment {
        /**
         * The fragment argument representing the section number for this
         * fragment.
         */
        private static final String ARG_SECTION_NUMBER = "section_number";

        /**
         * Returns a new instance of this fragment for the given section
         * number.
         */
        public static PlaceholderFragment newInstance(int sectionNumber) {
            PlaceholderFragment fragment = new PlaceholderFragment();
            Bundle args = new Bundle();
            args.putInt(ARG_SECTION_NUMBER, sectionNumber);
            fragment.setArguments(args);
            return fragment;
        }

        public PlaceholderFragment() {
        }

        @Override
        public View onCreateView(LayoutInflater inflater, ViewGroup container,
                                 Bundle savedInstanceState) {
            View rootView = inflater.inflate(R.layout.fragment_main, container, false);
            return rootView;
        }

        @Override
        public void onAttach(Activity activity) {
            super.onAttach(activity);
            ((HistoryActivity) activity).onSectionAttached(
                    getArguments().getInt(ARG_SECTION_NUMBER));
        }
    }

    private class getHistoryAsyncRetriever
            extends AsyncTask<Void, Void, HistoryItemCollection> {

        /**
         * Updates UI to indicate that the list of nearby places is being
         * retrieved.
         */
    /*
    @Override
    protected void onPreExecute() {
        placesListLabel.setText(R.string.retrievingPlaces);
        MainActivity.this.setProgressBarIndeterminateVisibility(true);
    }
    */

        /**
         * Updates UI to indicate that retrieval of the list of nearby places
         * completed successfully or failed.
         */
        @Override
        protected void onPostExecute(final  HistoryItemCollection result) {
        /*
        MainActivity.this.setProgressBarIndeterminateVisibility(false);

        if (result == null || result.getItems() == null
                || result.getItems().size() < 1) {
            if (result == null) {
                placesListLabel.setText(R.string.failedToRetrievePlaces);
            } else {
                placesListLabel.setText(R.string.noPlacesNearby);
            }

            placesList.setAdapter(null);
            return;
        }

        placesListLabel.setText(R.string.nearbyPlaces);

        ListAdapter placesListAdapter = createPlaceListAdapter(
                result.getItems());
        placesList.setAdapter(placesListAdapter);

        places = result.getItems();
        */
        }


        @Override
        protected HistoryItemCollection doInBackground(Void... params) {

            HistoryItemCollection result;
            try {
                result = shoppingAssistantAPI.historyItems().getUserHistory().execute();
            } catch (IOException e) {
                String message = e.getMessage();
                if (message == null) {
                    message = e.toString();
                }
                LOG.warning("Exception when checking in =" + message);
                result = null;

            }
            if (result != null && result.getItems() != null)
                Log.i("History", "history result: "+result.getItems().get(0).toString());
            else
                Log.i("History", "history result is empty ");
            return result;
        }
    }
}
